using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace fAIConsole.RAG
{
    public  class RandomPeople
    {
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string birthday { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string profession { get; set; }

        public static RandomPeople FromJson(string json) => JsonConvert.DeserializeObject<RandomPeople>(json);

        /* The json file was generated by ChatGpt4 with the following prompt:
Generate a list of 200 random 
lastname,
firstname, 
birthday,
city and state in the usa, 
profession.
Insure a greater diversity in the choice of the firstname and lastname,
return the data in JSON format.

I need the complete data in a json file.
         */
        public static List<RandomPeople> FromFile(string filename) 
            => JsonConvert.DeserializeObject<List<RandomPeople>>(System.IO.File.ReadAllText(filename));

        public static string GenerateTextDataForPrompt(List<RandomPeople> people)
        {
            var sb = new StringBuilder();
            foreach(var p in people.Take(100))
            {
                //sb.AppendLine($"The person {p.firstname} {p.lastname} born on {p.birthday} in {p.city}, {p.state}; Work as a {p.profession}.");
                sb.AppendLine($"{p.firstname} {p.lastname} born on {p.birthday} in {p.city}, {p.state}; Job: {p.profession}.");
            }
            return sb.ToString();
        }
    }
}
